version: "3"
services:
  hub:
    image: selenium/hub:4.32
  chrome:
    image: selenium/node-chromium:4.32
    depends_on:
    - hub
    shm_size: '2g'
    deploy:
      replicas: 0
    env_file: .env
  firefox:
    image: selenium/node-firefox:4.32
    depends_on:
    - hub
    shm_size: '2g'
    deploy:
      replicas: 0 
    env_file: .env